---
services:
  redis:
    image: docker.io/library/redis:alpine
    container_name: felfel-redis
    command: redis-server --user ${REDIS_USERNAME} on \>${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands

  app:
    image: felfel:latest
    container_name: felfel-app
    build: .
    ports:
      - 8080:8080
    environment:
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  prometheus:
    image: bitnami/prometheus:latest
    container_name: felfel-prometheus
    volumes:
      - ${PWD}/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml:Z
    ports:
      - 9090:9090
